# ==============================================================
# = Eureka Server - Profilo peer3
# ==============================================================

server:
  port: 8763
  tomcat:
    max-threads: 5

spring:
  application:
    name: EurekaServer
eureka:
  instance:
    hostname: peer3
    metadataMap:
      zone: zone3
    preferIpAddress: true
    instanceId: ${spring.application.name}-3
  # ==============================================================
  # = Impostazione Server
  # ==============================================================
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
  # ==============================================================
  # = Impostazione Client
  # ==============================================================
  client:
    serviceUrl:
      defaultZone:  http://user:BimBumBam_2018@localhost:8761/eureka/,http://user:BimBumBam_2018@localhost:8762/eureka/

sicurezza:
  userpwd: ${uspwd}
  adminpwd: ${adpwd}

jasypt:
  encryptor:
    # password passata come variabile da linea di comando al comando mvn di build per produrre un jar con già valorizzata questa property. Es.: mvn clean install -Denpwd=123_Stella.
    password: ${enpwd}

# ==============================================================
# = Logs Parameters
# ==============================================================
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.security: INFO