# ==============================================================
# = Spring API Gateway - Versione Test
# ==============================================================
server:
  port: 8765
  #port: 876${seq}
  tomcat:
    threads:
      max: 5
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      httpclient:
        #Timeout di connessione in ms
        connect-timeout: 2000 #2s
        #Timeout di risposta in s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - name: RequestRateLimiter
          args:
            # filtro redis serve per limitare il numero di chiamate accettate per utente al secondo (per evitare attacchi DDoS)
            #Numero di token inseriti nel bucket al secondo (se in 1 secondo vengono inseriti più di 10 token nel bucket di redis, quindi abbiamo più di 10 chiamate al secondo, allora redis interverrà...)
            # It's how many requests per second do you want a user to be allowed to do, without any dropped requests.
            # This is the rate that the token bucket is filled.
            redis-rate-limiter.replenishRate: 10
            #Picco di token per utente inseriti nel bucket in un secondo
            # Es.: se un utente raggiunge al secondo 0 le 20 richieste massime consentite, ed ogni secondo ne recupera 10, dovrà attendere fino al secondo 3 per poter fare nuove chiamate....
            # It's the maximum number of requests a user is allowed to do in a single second.
            # This is the number of tokens the token bucket can hold.
            # Setting this value to zero will block all requests.
            redis-rate-limiter.burstCapacity: 10
            #Numero di token per ciascuna chiamata (ogni chiamata inserisce 1 token nel bucket del redis)
            redis-rate-limiter.requestedTokens: 1
            #key-resolver: '#{@userKeyResolver}'
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      enabled: true

      # ==============================================================
      # = Route Parameters
      # ==============================================================
      routes:
        - id: cacheArticoliModule
          uri: lb://ProductsWebService
          predicates:
            - Path=/api/articoli-cache/**
        - id: articoliModule
          uri: lb://ProductsWebService
          predicates:
            - Path=/api/articoli/**
          filters:
            - name: CircuitBreaker
              args:
                name: articoliCircuitBreaker
                fallbackUri: forward:/articolo-fallback
        - id: cachePrezziModule
          uri: lb://PriceArtWebService
          predicates:
            - Path=/api/prezzi-cache/**
        - id: prezziModule
          uri: lb://PriceArtWebService
          predicates:
            - Path=/api/prezzi/**
          filters:
            - name: CircuitBreaker
              args:
                name: prezziCircuitBreaker
                fallbackUri: forward:/prezzo-fallback
        - id: listinoModule
          uri: lb://PriceArtWebService
          predicates:
            - Path=/api/listino/**
        - id: authModule
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: cachePromoModule
          uri: lb://PromoPrezziWebService
          predicates:
            - Path=/api/promo-cache/**
        - id: prezziPromoModule
          uri: lb://PromoPrezziWebService
          predicates:
            - Path=/api/promo/prezzo/**
        - id: promoModule
          uri: lb://PromoPrezziWebService
          predicates:
            - Path=/api/promo/**
  # ==============================================================
  # = Redis Parameters
  # ==============================================================
  redis:
    connect-timeout: 2s
    host: localhost
    #password: password
    port: 6379
    timeout: 1s
  # ==============================================================
  # = Zipkin Parameters
  # ==============================================================
  zipkin:
    base-url: http://localhost:9411/
    sender:
      # invio eventi sincrono
      type: web
      # invio eventi asincrono
    #      type: rabbit
    message-timeout: 5
  # ==============================================================
  # = Sleuth Parameters
  # ==============================================================
  sleuth:
    sampler:
      # probability: varia da 1.0 a 0.0. 1.0: qualsiasi evento inserito nei log sarà anche inviato allo sleuth (ed inviato allo zipkin); 0.0 non invia nulla
      probability: 1.0
    # se true, genera un identificativo univoco per ogni richiesta di 128 bit; se falso ne genera uno da 64 bit
    trace-id128: false

# ==============================================================
# = Resilience4j Parameters
# ==============================================================
resilience4j:
  circuitbreaker:
    configs:
      default:
        #soglia in percentuali di fallimenti che che determina l'apeWrtura del circuito
        failureRateThreshold: 50
        #numero di chiamate di riferimento
        slidingWindowSize: 5
        #tempo di durata dello stato di circuito aperto
        wait-duration-in-open-state: 20000
        #numero di chiamate in stato half open
        permittedNumberOfCallsInHalfOpenState: 5
        #Se impiega più di un secondo viene conteggiato come lento
        slow-call-duration-threshold: 1000
        slow-call-rate-threshold: 50.00

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s

#==============================================================
# = Logs Parameters
# ==============================================================
logging:
  file:
    name: "/home/cristian/tmp/Udemy/spring-cloud-course/logs/GatewaySrv.log"
  pattern:
    file: "%d{ dd-MM-yyyy HH:mm:ss.SSS } [%thread] %-5level %logger{36} - %msg%n"
    #    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    console: "%d{dd.MM.yyyy HH:mm:ss.SSS} %-5p - [%C]:%m%n"
  logback:
    rollingpolicy:
      max-file-size: 1MB
  level:
    org:
      springframework:
        security: DEBUG
        cloud: DEBUG
    io:
      github:
        resilience4j: DEBUG
    #org.springframework.security: DEBUG

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
sicurezza:
  header: Authorization
  secret: $123_Stella@xantrix.it

management:
  endpoints:
    web:
      exposure:
        include: '*'